version: '3'

volumes:
  mysql_data:
    driver: local

services:

  traefik:
    image: traefik:v2.1
    container_name: traefik-um-shoss
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infra
      - smarthomeoss


  mysql:
    image: mysql:8.0.19
    container_name: mysql-um-shoss
    volumes:
      - ~/.smart-home/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 8306:3306
    networks:
      - infra
      - smarthomeoss

  keycloak:
    image: quay.io/keycloak/keycloak:9.0.0
    container_name: keycloak-um-shoss
    volumes:
      - ~/.smart-home/keycloak_tmp:/tmp
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.rule: Host(`keycloak.localhost`)
      traefik.http.routers.keycloak.entrypoints: web
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
#      JDBC_PARAMS: "connectTimeout=30000&useSSL=false"
    ports:
      - 8887:8080
    networks:
      - infra
      - smarthomeoss
    depends_on:
      - mysql

# https://github.com/consul/consul/blob/master/docker-compose.yml

    # service configuration for our dockerized Rails app
  consul:
    container_name: consul-um-shoss
    image: consul:1.7.1
    depends_on:
      - mysql
    ports:
      - 8301:8301
      - 8302:8302
      - 8600:8600
      - 8500:8500
      # gui port
    networks:
      - infra
      - smarthomeoss

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    container_name: zookeeper-um-shoss
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - infra
      - smarthomeoss

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka-um-shoss
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - infra
      - smarthomeoss
    ports:
      - 10049:9092

networks:
  smarthomeoss:
    external: true
  infra:
    internal: true